services:
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - backend
  
  backend:
    build: ./backend
    ports:
      - "8002:8001"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - /mnt/nas/uploads:/backend/uploads
